name: Node CI

on: [push]

jobs:
  build:
    name: first build job
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2  
    - uses: actions/setup-node@v1
      with:
        node-version: 12.x
          
    - name: Install dependencies
      run: yarn install

    - name: Release
      uses: cycjimmy/semantic-release-action@v2
      #run: yarn semantic-release  
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      if: github.event_name == 'push'
      
    
